# LXD API 配置文件

# 系统配置
system:
  # 服务器配置
  server:
    # API服务端口
    port: 8080
    # 服务模式 (debug=详细日志+错误堆栈, release=精简日志+生产优化)
    mode: release
    # TLS配置 - 强制启用HTTPS/WSS
    tls:
      cert_file: "server.crt"         # SSL证书文件路径
      key_file: "server.key"          # SSL私钥文件路径
      auto_gen: true                  # 自动生成自签证书
      server_ips:                     # 服务器IP列表（用于证书SAN）
        - "PUBLIC_NETWORK_IP_ADDRESS"           # 外网IP
  # 安全配置
  security:
    # API访问hash (用于验证请求) - hash验证必须开启
    # 注意：这个hash需要与ZJMF系统中lxdserver插件配置的accesshash一致
    api_hash: "API_ACCESS_HASH"
    # 是否启用认证日志
    enable_log: false
  # 数据库配置
  database:
    # 数据库文件路径
    path: "lxdapi.db"
    # 是否启用数据库日志
    enable_log: false
  # LXC命令配置
  lxc:
    # 普通命令超时时间(秒)
    timeout: 60
    # 长时间操作超时时间(秒) - 如创建、重装容器
    long_timeout: 300
    # 是否启用详细日志
    verbose: false
  # CORS跨域配置 - 用于Web控制台访问
  cors:
    # 允许的源 (生产环境建议配置具体域名)
    allow_origins: ["*"]
    # 是否允许凭证
    allow_credentials: true

# 任务状态查询配置
task_status:
  # 是否启用任务状态查询日志
  enable_log: false
  # 任务数据保留时间
  retention_hours: 168

# 容器管理接口配置
container_api:
  # 是否启用容器管理接口日志
  enable_log: false
  # 是否记录详细的操作参数
  log_params: false
  # 是否记录操作结果
  log_results: true

# 容器状态查询接口配置
container_status:
  # 是否启用容器状态查询接口日志
  enable_log: false
  # 是否记录查询参数
  log_params: true
  # 是否记录查询结果
  log_results: true

# 流量统计接口配置
traffic_api:
  # 统计间隔（秒）
  interval: 5
  # 是否启用流量统计接口日志
  enable_log: false
  # 是否记录查询参数
  log_params: true
  # 是否记录查询结果
  log_results: true
  # 流量限制检测配置
  limit_check:
    # 检测间隔（秒）
    check_interval: 5
    # 是否启用流量限制检测日志
    enable_log: false
  # 自动流量重置配置
  auto_reset:
    # 检查间隔（秒）
    check_interval: 360
    # 是否启用自动重置日志
    enable_log: false

# NAT端口转发接口配置
nat_api:
  # 是否启用NAT接口日志
  enable_log: false
  # 是否记录操作参数
  log_params: true
  # 是否记录操作结果
  log_results: true

# Web控制台接口配置
console_api:
  # 是否启用控制台接口日志
  enable_log: false
  # 是否记录操作参数
  log_params: true
  # 是否记录操作结果
  log_results: true
  # 控制台会话超时时间(秒)
  session_timeout: 1800