# LXD API 服务配置文件

# 系统配置
system:
  server:
    port: 8080                    # API服务端口
    mode: release                 # 运行模式: debug | release
    tls:
      cert_file: "server.crt"      # SSL证书文件
      key_file: "server.key"       # SSL私钥文件
      auto_gen: true              # 自动生成自签证书
      server_ips:
        - "137.131.244.135"          # 服务器外网IP
  security:
    api_hash: "3DF7385168CFA249"     # API访问验证密钥
    enable_log: false              # 启用认证日志
  database:
    path: "lxdapi.db"             # 数据库文件路径
    enable_log: false             # 数据库操作日志
  lxc:
    verbose: false                # LXC命令详细日志
  cors:
    allow_origins: ["*"]          # 跨域访问源（生产环境建议限制）
    allow_credentials: true       # 允许携带凭证

# 容器管理接口
container_api:
  enable_log: true               # 容器操作日志
  
# 内部任务执行机制
task_status:
  enable_log: false               # 任务执行日志
  retention_hours: 168            # 任务记录保留时间（小时）

# 容器状态查询
container_status:
  enable_log: false               # 状态查询日志

# 流量统计
traffic_api:
  interval: 5                     # 统计间隔（秒）
  enable_log: false               # 流量统计日志
  limit_check:
    check_interval: 5             # 限制检测间隔（秒）
    enable_log: false             # 限制检测日志
  auto_reset:
    check_interval: 360           # 自动重置检查间隔（秒）
    enable_log: false             # 重置日志

# NAT端口转发
nat_api:
  enabled: false                   # NAT功能总开关
  enable_log: false               # NAT操作日志
  ipv6_support: false              # IPv6 NAT支持开关
  network:
    external_interface: "enp0s3"         # 外网网卡
    external_ips: ["10.0.0.16"]              # 外网IPv4地址列表
    external_ipv6s: ["2604:4300:a:33a:78ec:1296:7c1b:7434"]            # 外网IPv6地址列表
    internal_interface: "lxdbr0"   # 内网网卡
  container_ip:
    preferred_interfaces: ["eth0"] # 优先网卡
    ignored_interfaces: ["docker0", "br-"] # 忽略网卡

# Web控制台
console_api:
  enable_log: false                # 控制台日志
  session_timeout: 1800           # 会话超时（秒）

# IPv6独立绑定
ipv6_binding:
  enabled: false                 # IPv6绑定功能总开关
  enable_log: false               # IPv6绑定操作日志
  interface: "wg0"                # IPv6绑定网卡接口
  ipv6_pool:
    start: "2a11:6c7:f05:156::6666"      # IPv6地址池起始地址
    prefix_length: 64             # IPv6前缀长度
    pool_size: 1000              # 地址池大小