system:
  server:
    # 服务端口
    port: ${SERVER_PORT}
    # 运行模式 debug | release
    mode: release
    tls:
      # TLS 证书文件路径
      cert_file: "server.crt"
      # TLS 私钥文件路径
      key_file: "server.key"
      # 是否自动生成自签名证书
      auto_gen: true
      # 服务器外网 IP 列表（用于证书 SAN）
      server_ips:
        - "${PUBLIC_NETWORK_IP_ADDRESS}"
  
  security:
    # API 访问验证密钥
    api_hash: "${API_ACCESS_HASH}"
    # 是否记录认证日志
    enable_log: false
  
  database:
    # 数据库类型 sqlite | mysql | mariadb | postgres
    type: "${DB_TYPE}"
    # 是否记录数据库操作日志
    enable_log: false
    
    # SQLite 配置
    sqlite_path: "lxdapi.db"
    
    # MySQL/MariaDB 配置
    mysql_host: "${DB_MYSQL_HOST}"
    mysql_port: ${DB_MYSQL_PORT}
    mysql_user: "${DB_MYSQL_USER}"
    mysql_password: "${DB_MYSQL_PASSWORD}"
    mysql_database: "${DB_MYSQL_DATABASE}"
    mysql_charset: "utf8mb4"
    
    # PostgreSQL 配置
    postgres_host: "${DB_POSTGRES_HOST}"
    postgres_port: ${DB_POSTGRES_PORT}
    postgres_user: "${DB_POSTGRES_USER}"
    postgres_password: "${DB_POSTGRES_PASSWORD}"
    postgres_database: "${DB_POSTGRES_DATABASE}"
    # SSL 模式 disable | require | verify-ca | verify-full
    postgres_sslmode: "disable"
    # 时区设置
    postgres_timezone: "Asia/Shanghai"
    
    # 连接池配置（MySQL/MariaDB/PostgreSQL）
    max_idle_conns: 10
    max_open_conns: 100
    # 连接最大生存时间（秒）
    conn_max_lifetime: 3600
    
    # 兼容旧版本配置字段
    path: "lxdapi.db"
  
  lxc:
    # 是否输出 LXC 命令详细日志
    verbose: false
  
  cors:
    # 允许跨域的源列表
    allow_origins: ["*"]
    # 是否允许携带凭证
    allow_credentials: true

logging:
  # 日志文件保存路径
  file: "/var/log/lxdapi/app.log"
  # 单个日志文件最大大小（MB）
  max_size: 100
  # 保留的旧日志文件数量
  max_backups: 10
  # 保留的旧日志文件天数
  max_age: 30
  # 是否压缩旧日志文件
  compress: true

task_queue:
  # 队列后端类型 database | redis
  backend: "${QUEUE_BACKEND}"
  # Worker 并发数量
  worker_count: 5
  # 轮询间隔（毫秒，仅 database 后端使用）
  poll_interval: 100
  # 失败任务最大重试次数
  max_retries: 3
  # 是否记录任务队列日志
  enable_log: false
  
  # Redis 配置（backend=redis 时生效）
  redis_host: "${REDIS_HOST}"
  redis_port: ${REDIS_PORT}
  redis_password: "${REDIS_PASSWORD}"
  redis_db: 0

task_status:
  # 是否记录任务状态日志
  enable_log: false
  # 任务记录保留时间（小时）
  retention_hours: 168

container_api:
  # 是否记录容器操作日志
  enable_log: false
  # 存储池列表（按顺序尝试）
  storage_pools: [${STORAGE_POOLS}]

container_status:
  # 是否记录容器状态查询日志
  enable_log: false

traffic_api:
  # 流量统计间隔（秒）
  interval: 5
  # 每批处理的容器数量
  batch_size: 10
  # 是否记录流量统计日志
  enable_log: false
  
  limit_check:
    # 流量限制检测间隔（秒）
    check_interval: 5
    # 每批检查的容器数量
    batch_size: 10
    # 是否记录限制检查日志
    enable_log: false
  
  auto_reset:
    # 自动重置检查间隔（秒）
    check_interval: 360
    # 每批重置检查的容器数量
    batch_size: 10
    # 是否记录自动重置日志
    enable_log: false

nat_api:
  # NAT 端口转发功能总开关
  enabled: ${NAT_SUPPORT}
  # 是否记录 NAT 操作日志
  enable_log: false
  # 是否支持 IPv6 NAT
  ipv6_support: ${IPV6_NAT_SUPPORT}
  
  network:
    # 外网网卡接口名称
    external_interface: "${NETWORK_EXTERNAL_INTERFACE}"
    # 外网 IPv4 地址列表
    external_ips: ["${NETWORK_EXTERNAL_IPV4}"]
    # 外网 IPv6 地址列表
    external_ipv6s: ["${NETWORK_EXTERNAL_IPV6}"]
    # 内网网卡接口名称
    internal_interface: "lxdbr0"
  
  container_ip:
    # 优先使用的容器网卡
    preferred_interfaces: ["eth0"]
    # 忽略的网卡前缀
    ignored_interfaces: ["docker0", "br-"]

ipv6_binding:
  # IPv6 独立绑定功能总开关
  enabled: ${IPV6_BINDING_ENABLED}
  # 是否记录 IPv6 绑定日志
  enable_log: false
  # IPv6 绑定使用的网卡接口
  interface: "${IPV6_BINDING_INTERFACE}"
  
  ipv6_pool:
    # IPv6 地址池起始地址
    start: "${IPV6_POOL_START}"
    # IPv6 前缀长度
    prefix_length: 64
    # 地址池大小
    pool_size: 9999

console_api:
  # 是否记录 Web 控制台日志
  enable_log: false
  # 会话超时时间（秒）
  session_timeout: 1800

proxy_api:
  # 反向代理功能总开关
  enabled: ${NGINX_PROXY_ENABLED}
  # 是否记录代理操作日志
  enable_log: false