server:
  address: "0.0.0.0:3000" # 服务器地址
  mode: "release" # 运行模式: debug | release
  session_secret: "GgUM6g7jJuAXaL3NzBNmB2z27EITb2#CfbHy$CA9JwQWL4%sPxJD%BfE2r3UC#zn" # 会话密钥

database:
  path: "lxdweb.db" # 数据库文件路径

sync:
  interval: 3600 # 同步间隔秒
  batch_size: 5 # 每批同步个
  batch_interval: 5 # 批次间隔秒
